### ISSUE TITLE
创建canvas的时候的问题

### ISSUE THREAD

**Issue by DonyZ-V** [xd-tayde/mcanvas#1]
![20](https://user-images.githubusercontent.com/16370137/29302451-dc233ff4-81b6-11e7-9959-b0524d2bf638.png)

**Comment by xd-tayde** [comment]
因为这个是基于浏览器环境的，暂时不支持node环境的使用。

**Comment by DonyZ-V** [comment]
那就是说没有办法批量修改？

**Comment by xd-tayde** [comment]
你需要批量修改什么呢。？

**Comment by DonyZ-V** [comment]
就是在图片上加上水印，而且就以图片的名字作为水印，所以每张图片的水印都是不同的

**Comment by xd-tayde** [comment]
在node环境暂时是做不到的，不过在浏览器环境是可以的。
