### ISSUE TITLE
字体颜色设置不生效，请问是什么问题呢？

### ISSUE THREAD

**Issue by WangMargin** [xd-tayde/mcanvas#17]
let mc = new MC({
					// 					width: 1000,
					// 					height: 1000,
					// 					backgroundColor: 'black',
				});

				// background : 准备底图；提供多种模式
				mc.background(bg, {
						left: 0,
						top: 0,
						color: '#FFFFFF',
						type: 'origin',
					})
					// add 添加图片素材基础函数；
					.add(userHeadImg, {
						width: 130,
						height: 130,
						pos: {
							x: 30,
							y: 30,
							rotate: 1,
						},
					})

					// add 添加图片素材基础函数；
					.add(ercode, {
						width: 200,
						pos: {
							x: 515,
							y: 1090,
						},
					})

					// text 添加文字数据基础函数；
					.text(user.nickname, {
						width: '300px',
						smallStyle: {
							// 字体颜色；
							color: '#ffffff',
						},
						pos: {
							x: 180,
							y: 50,
						},
					})
					.text(shareDesc, {
						width: '300px',
						smallStyle: {
							// 字体颜色；
							color: '#FFF',
							// 文字渐变
							gradient: {
								type: 2, // 1: 横向渐变； 2: 纵向渐变；
								colorStop: ['red', 'blue'],
							},
						},
						pos: {
							x: 180,
							y: 90,
						},
					})

					// draw 最终绘制函数，用于最终的绘制；
					.draw(b64 => {
						that.$data.shareCanvasImg = b64
					});

**Comment by xd-tayde** [comment]
尝试这样看看会不会生效：
smallStyle:{
     color:'#ffffff',
     font:'50px Microsoft YaHei,sans-serif',
}

**Comment by WangMargin** [comment]
您好  我修改完之后 未生效  您看我是哪里修改错误了么 【字体颜色还是 黑色的】


                                let mc = new MC({
					// 					width: 1000,
					// 					height: 1000,
					// 					backgroundColor: 'black',
				});
				
				
				// background : 准备底图；提供多种模式
				mc.background(bg, {
						left: 0,
						top: 0,
						color: '#FFFFFF',
						type: 'origin',
					})
					// add 添加图片素材基础函数；
					.add(userHeadImg, {
						width: 130,
						height: 130,
						pos: {
							x: 30,
							y: 30,
							rotate: 1,
						},
					})
				
					// add 添加图片素材基础函数；
					.add(ercode, {
						width: 200,
						pos: {
							x: 515,
							y: 1090,
						},
					})
				
					// text 添加文字数据基础函数；
					.text('MyUserName' ,{
						width: '300px',
						
						pos: {
							x: 180,
							y: 50,
						},
					})
					.text('HELLO WORLD', {
						width: '300px',
						smallStyle:{
							color:'#ffffff',
							font:'50px Microsoft YaHei,sans-serif',
						},
				
						pos: {
							x: 180,
							y: 90,
						},
					})
				
					// draw 最终绘制函数，用于最终的绘制；
					.draw(b64 => {
						that.$data.shareCanvasImg = b64
					});






------------------ 原始邮件 ------------------
发件人: "郭东东(Tayde Guo)"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 下午5:45
收件人: "xd-tayde/mcanvas"<mcanvas@noreply.github.com>;
抄送: "吃着皮皮虾的超哥"<916118932@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xd-tayde/mcanvas] 字体颜色设置不生效，请问是什么问题呢？ (#17)




尝试这样看看会不会生效：
 smallStyle:{
 color:'#ffffff',
 font:'50px Microsoft YaHei,sans-serif',
 }

**Comment by xd-tayde** [comment]
哦。~我知道了。 .text('HELLO WORLD') 对应的是 normalStyle。。 你写的 smallStyle 需要使用 .text('<s>HELLO WORLD</s>')

**Comment by WangMargin** [comment]
感谢感谢   问题已经解决了  给大佬点赞
