### ISSUE TITLE
想知道引用mcanvas.min.js后为什么找不到MCanvas呢?

### ISSUE THREAD

**Issue by flyjin** [xd-tayde/mcanvas#19]
引入之后 直接new Mcanvas()  提示找不到 请教该如何使用呢?  能不能像jQuery一样那样 引入js后 直接使用呢?  前端菜鸟,跪求大神解答

**Comment by flyjin** [comment]
是不是还需要引入别的文件 还是怎么使用

**Comment by flyjin** [comment]
我是普通的那种网页  不是vue  也不是react

**Comment by flyjin** [comment]
Uncaught TypeError: window.MCanvas is not a constructor

**Comment by flyjin** [comment]
html中这样引用的
`<script` type='text/javascript' src='../../public/mcanvas.js' charset='utf-8'></script>`
js然后直接new window.Mcanvas  报错
提示
`Uncaught TypeError: window.MCanvas is not a constructor`

**Comment by flyjin** [comment]
解决了 发现得  var mc = window.MCanvas.default()这样写才行

**Comment by xd-tayde** [comment]
sorry。。没及时回复~这个应该是打包的问题。我回头修复下哈。感谢
