### ISSUE TITLE
好好的库，为什么字体大小固定3种啊，强烈建议修改成自定义大小的啊

### ISSUE THREAD

**Issue by ieliwb** [xd-tayde/mcanvas#2]
RT

**Comment by xd-tayde** [comment]
可以自定义字体大小呀。。可以通过 smallStyle / normalStyle / largeStyle 分别修改大中小号字体的样式，包括 字体/字号/颜色/行高；

**Comment by ieliwb** [comment]
好像只有这3种啊，支持font-size吗？
 font : ``,
        color:'#000',
        lineheight: 100,

**Comment by xd-tayde** [comment]
font属性是类似于css里的font，也可以修改大小的。font:italic bold 12px/20px arial,sans-serif;

**Comment by ieliwb** [comment]
这样啊，谢谢指点啊 @xd-tayde

**Comment by zhouf88** [comment]
@ieliwb 你搞定了吗？我按上面的提示，没生效

**Comment by ieliwb** [comment]
@zhouf88 实现的不是很完美哦，不知道是我方法不对，还是这个库有小bug😂，勉强用吧，看我网站效果：字体好像渐变了，不知道什么原因
http://91guodong.com/show/4244044

**Comment by zhouf88** [comment]
@xd-tayde @ieliwb largeStyle:{
                        font:'20px', //文字大小是写这个里面？好像不能写 font-size:"20px"
                        color:'#000',
                        lineheight: 100,
                    },没搞明白，忘指点下

**Comment by xd-tayde** [comment]
是的。~font值暂时只能支持完整的css方式，如
.text(`${data.honor}`,{
                width: 750,
                align: 'center',
                normalStyle:{
                    font:`bold 85px Microsoft YaHei,sans-serif`,
                    color:'#d42025',
                },
                pos:{
                    x:2,
                    y:363,
                },
            })

之后有时间会进行下优化。。感谢使用。

**Comment by zhouf88** [comment]
@xd-tayde 谢谢啊
