### ISSUE TITLE
图片上插入文字，文字有些模糊

### ISSUE THREAD

**Issue by ZhengLiJing** [xd-tayde/mcanvas#26]
const that = this;
    const mc = new MC({
      width: 684,
      height: 214,
      backgroundColor: '#fff'
    });
    
    mc.background('https://view.didistatic.com/static/dcms/5p5vwvyjrfk8zkurgo_684x219_compress.png', {
      left: 0,
      top: 0,
      type: 'origin',
    }).text('迎新年发劵', {
      pos: {
        x: 38,
        y: 30,
      },
      normalStyle: {
        font: '36px Microsoft YaHei,sans-serif',
      }
    }).text('加油8.8折 轻松享受', {
      pos: {
        x: 44,
        y: 88 - 9,
      },
      normalStyle: {
        font: '300 24px Microsoft YaHei,sans-serif',
        color: '#a6a6a6',
      }
    }).text('立即领取', {
      pos: {
        x: 54,
        y: 134,
      },
      normalStyle: {
        font: '20px Microsoft YaHei,sans-serif',
        color: 'white',
      }
    }).draw({
      type: 'jpg',
      quality: 1,
      success(b64) {
        that.setState({
          pic: b64,
        });
      },
      error(err) {
        console.log('err=', err);
      }
    });

**Comment by xd-tayde** [comment]
新版本2.0 已经发布，试下还会不会又该问题。感谢
