### ISSUE TITLE
emhance project for Node.js support

### ISSUE THREAD

**Issue by JesseWeb** [xd-tayde/mcanvas#27]
Node side has image merge demand. And in most cases. [node-canvas](https://github.com/Automattic/node-canvas) has a same api compare to Web-Based Canvas.

**Comment by JesseWeb** [comment]
we can implement `Canvas` 、`Image` in constructor  option. for web-based `Canvas` and `Image` Objects replacement;

Here is a usage example: 
```
// Node.js environment.
import {Canvas,Image} from "canvas";
let imageInstance = new MCanvas({
    width: 1000,
    height: 1500,
    Canvas,
    Image
});
imageInstance.dosth().dosth()...
```

**Comment by JesseWeb** [comment]
waiting for discussion.

**Comment by JesseWeb** [comment]
talking about node, maybe we can discus about typescript. I didn't found type file in this repository.
should we write a `d.ts` file compliant  typescript ?

**Comment by xd-tayde** [comment]
forgive me for late.  Thanks..i will write in my todo list for supporting node.js and typescript. expect for next version.. Thanks!

**Comment by JesseWeb** [comment]
its fine. anything I can help when you got the idea with that.

**Comment by xd-tayde** [comment]
> its fine. anything I can help when you got the idea with that.

Now new 2.0 version has published and it can use in Node.js. try again, any problem contact me

**Comment by JesseWeb** [comment]
nice job
