### ISSUE TITLE
请问是否支持react native，用于开发App？

### ISSUE THREAD

**Issue by haobrother** [xd-tayde/mcanvas#29]
你好，目前我使用react native进行App开发，打算实现图像的绘制（合成），我看到你的库好像能够方便实现这个功能，但是基于Canvas，我试了下好像是用不了，请问有什么别的库推荐支持RN的吗？

**Comment by xd-tayde** [comment]
在RN上应该无法使用，现在并没有做兼容。

**Comment by haobrother** [comment]
> 在RN上应该无法使用，现在并没有做兼容。

感谢回复，我已经找到解决方案，谢谢！
