### ISSUE TITLE
可以考虑开放textBaseline属性设置吗

### ISSUE THREAD

**Issue by xxf1996** [xd-tayde/mcanvas#32]
如题，由于需要做一个图片加文字的合成功能，文字可拖拽编辑那种；但是看源码目前text绘制时textBaseline固定为alphabetic，会导致输出的文字位置偏下；

![image](https://user-images.githubusercontent.com/17797002/85990814-25dcb900-ba25-11ea-8d6d-d80c1273253f.png)

基线位置不符合我这边的需求，可以开放textBaseline属性吗？

**Comment by xd-tayde** [comment]
因为 textBase 涉及到换行的计算，如果是别的值，可能会导致问题，暂时不打算开放；你这个需求建议可以使用 lineHeight + pox.y 来定位解决。。感谢使用，有什么问题随时喊我。
