### ISSUE TITLE
英文单词自动换行被切割

### ISSUE THREAD

**Issue by AprildreamMI** [xd-tayde/mcanvas#33]
# 英文单词自动换行被切割
+ 建议加一个选项，自动换行的时候对于一个完整的英文单词是否要换行来完整显示还是被切割显示
+ 或者加入换行相关样式参数，让用户自定义

**Comment by xd-tayde** [comment]
好的~感谢建议。。我想办法新增下这个规则。

**Comment by xd-tayde** [comment]
您好，最新版本2.0.6已经支持设置是否断词的功能了哈~~ 在 text 中 style 中新增 wordBreak 属性；

**Comment by AprildreamMI** [comment]
> 您好，最新版本2.0.6已经支持设置是否断词的功能了哈~~ 在 text 中 style 中新增 wordBreak 属性；有什么问题随时给我留言。

好的，谢谢~，等有机会再来体验体验
