### ISSUE TITLE
1.3.9版本因为背景图片有阴影，所以生成一圈黑色边框

### ISSUE THREAD

**Issue by AprildreamMI** [xd-tayde/mcanvas#34]
之前有个BUG是单边有黑色边框，现在又出现了是**背景图有阴影**的话，阴影处变成黑边，**黑边大小受阴影大小决定**

**Comment by xd-tayde** [comment]
能否把图片和问题截图发给我看下。我尽快解决。

**Comment by AprildreamMI** [comment]
> 能否把图片和问题截图发给我看下。我尽快解决。感谢

额额，不好意思，这个图片根据用户数据生成的，涉及到项目隐私问题，不好发出
不过应该可以复现的，找一张**带有阴影的图片**当背景，然后在上面渲染文本，生成为jpg，质量为0.9（目前参数是这样的）的图片，就会有一圈黑色边框

**Comment by xd-tayde** [comment]
我大概明白了~因为通常情况下，阴影是有渐变半透明的~而你导出的 jpg 是不支持透明度的。因此会出现阴影变成黑圈的情况。你试着导出 png 格式的图片看看。

**Comment by AprildreamMI** [comment]
> 我大概明白了。通常情况下，阴影是有渐变半透明的~而你导出的 jpg 是不支持透明度的。因此会出现阴影变成黑圈的情况。你试着导出 png 格式的图片看看。

导出为png确实不会，可能是这个原因
