### ISSUE TITLE
add 的 图片能基于素材本身的宽度吗

### ISSUE THREAD

**Issue by tradzero** [xd-tayde/mcanvas#6]
现在默认是根据画布的百分比吧 然后如果每个都要自己写width的话 感觉工作量很大 能否基于素材本身宽度呢

**Comment by tradzero** [comment]
@xd-tayde 
1. 意思就是默认百分比基于素材自身 我现在的方法是在外部获取图片资源 然后保存width 传入参数 但是我建议还是希望能基于图片自身宽度自适应
2 这个后来解决了 非常感谢
再次感谢 东西很棒

**Comment by xd-tayde** [comment]
了解。~我后续试试增加这种基于原图尺寸的模式哈。~感谢建议。
